version: '3.8'

services:
  nginx:
    container_name: nginx-container
    image: ssolmoon/dart-nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
      - database
    networks:
      - dart-network
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  database:
    container_name: mysql-container
    image: mysql:latest
    restart: always
    expose:
      - "3306"
    networks:
      - dart-network
    volumes:
      - ec2-user_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - ./.env

  redis:
    container_name: redis-container
    image: redis:latest
    restart: always
    expose:
      - "6379"
    networks:
      - dart-network
    env_file:
      - ./.env

  app:
    container_name: dart-container
    image: ssolmoon/dart:latest
    restart: always
    expose:
      - "8080"
    depends_on:
      - database
      - redis
    networks:
      - dart-network
    env_file:
      - ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=dev

networks:
  dart-network:
    driver: bridge

volumes:
  ec2-user_db_data:
    driver: local
