services:
  mysql:
    image: mysql:8.0.28
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - dart-network

  app:
    image: ${DOCKERHUB_USERNAME}/${PROJECT_NAME}
    container_name: dart
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JWT_SECRET_ACCESS_KEY: ${SPRING_JWT_SECRET_ACCESS_KEY}
      SPRING_JWT_ACCESS_EXPIRE: ${SPRING_JWT_ACCESS_EXPIRE}
      KAKAO_CLIENT_ID: ${KAKAO_CLIENT_ID}
      KAKAO_CLIENT_SECRET: ${KAKAO_CLIENT_SECRET}
      KAKAO_REDIRECT_URI: ${KAKAO_REDIRECT_URI}
      KAKAO_ADMIN_KEY: ${KAKAO_ADMIN_KEY}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - dart-network
    volumes:
      - ./application-dev.yml:/config/application-dev.yml

networks:
  dart-network:
    driver: bridge
