version: '3.8'

services:
  nginx:
    container_name: nginx-container
    image: ssolmoon/dart-nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
      - database
    networks:
      - dart-network
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt

  redis:
    container_name: redis-container
    image: redis:latest
    restart: always
    expose:
      - "6379"
    networks:
      - dart-network
    env_file:
      - ./.env

  app:
    container_name: dart-container
    image: ssolmoon/dart:latest
    restart: always
    expose:
      - "8080"
    depends_on:
      - redis
    networks:
      - dart-network
    env_file:
      - ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=dev

networks:
  dart-network:
    driver: bridge
