version: '3.8'

services:
  nginx:
    container_name: nginx-container
    image: ssolmoon/dart-nginx:latest
    restart: always
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    depends_on:
      - app
    networks:
      - dart-network
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
    env_file:
      - ./.env

  redis:
    container_name: redis-container
    image: redis:latest
    restart: always
    expose:
      - "${REDIS_PORT}"
    networks:
      - dart-network
    env_file:
      - ./.env

  app:
    container_name: dart-container
    image: ssolmoon/dart:latest
    restart: always
    expose:
      - "${APP_PORT}"
    depends_on:
      - redis
    networks:
      - dart-network
    env_file:
      - ./.env
    environment:
      - SPRING_PROFILES_ACTIVE=dev

networks:
  dart-network:
    driver: bridge
