name: DDU-A Build and Deploy to EC2

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: DockerHub Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Docker Image Build
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }} -f infra/Dockerfile .

      - name: DockerHub Push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.PROJECT_NAME }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/moduform
            
            if [ ! -f docker-compose.yml ]; then
              echo "docker-compose.yml not found!"
              exit 1
            fi

            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" | sudo tee .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" | sudo tee -a .env
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" | sudo tee -a .env
            echo "DB_URL=${{ secrets.DB_URL }}" | sudo tee -a .env
            echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" | sudo tee -a .env
            echo "PROJECT_NAME=${{ secrets.PROJECT_NAME }}" | sudo tee -a .env

            sudo /usr/local/bin/docker-compose down
            sudo /usr/local/bin/docker-compose pull
            sudo /usr/local/bin/docker-compose up -d
